# Generated by Django 5.1.7 on 2025-03-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_completed',
        ),
    ]
