# Generated by Django 5.1.7 on 2025-03-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
