# Generated by Django 5.1.7 on 2025-03-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_persons_last_name_persons_password_persons_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='assigned_to',
        ),
    ]
