# Generated by Django 5.1.7 on 2025-03-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='persons',
        ),
    ]
