# Generated by Django 5.1.7 on 2025-03-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_delete_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, null='True', upload_to='events_asset'),
            preserve_default='True',
        ),
    ]
